[package]
name = "memtest"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3

[dependencies]
num_cpus = "1.16.0"
packed_simd = "0.3.9"
rayon = "1.8.0"
termimad = "0.26.1"
